
export const USER_STEALTH_ADDRESS_COLLECTIONS = 'USER_STEALTH_ADDRESS_COLLECTIONS'
export const USER_STEALTH_ADDRESS_ACTIVED = 'USER_STEALTH_ADDRESS_ACTIVED'
export const ACTIVITY_STEALTH_ADDRESS  = 'ACTIVITY_STEALTH_ADRESS '

